PREFIX rr: <http://www.w3.org/ns/r2rml#>

# Inferences for shortcuts according to https://www.w3.org/TR/r2rml/#dfn-constant-shortcut-property

INSERT {
  ?s rr:graphMap [
    rr:constant ?o
  ]
}
WHERE {
  ?s rr:graph ?o
}

INSERT {
  ?s rr:subjectMap [
    rr:constant ?o
  ]
}
WHERE {
  ?s rr:subject ?o
}

INSERT {
  ?s rr:predicateMap [
    rr:constant ?o
  ]
}
WHERE {
  ?s rr:predicate ?o
}

INSERT {
  ?s rr:objectMap [
    rr:constant ?o
  ]
}
WHERE {
  ?s rr:object ?o
}
