#!/bin/sh

set -e
#set -x

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/config.pgsql ]; then
	. /usr/share/dbconfig-common/dpkg/config.pgsql 
	#dbc_authmethod_user="password"
	dbc_go sparqlify-tomcat-common $@
fi
