#!/bin/sh

set -e
#set -x

if [ -f /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.pgsql  ]; then
	. /usr/share/dbconfig-common/dpkg/postrm.pgsql 
fi
dbc_go sparqlify-tomcat-common $@

#DEBHELPER#
